### PR TITLE
Update README.adoc

### PR DESCRIPTION
**Pull request by arjantijms**
Update status to 1.1

### CODE REVIEW

**Comment by pavolloffay** [comment]
@arjantijms thanks for the PR. The IP validation is failing.

**Comment by pavolloffay** [comment]
I will close this, I don't want to have hardcoded version in readme. The version can be found in the spec or /releases github page

**Comment by arjantijms** [comment]
@pavolloffay Shall I make a new PR then to remove "Status: V 1.0 Released"?

Since now 1.0 is very much hardcoded right into the readme.

**Comment by pavolloffay** [comment]
I have submitted https://github.com/eclipse/microprofile-opentracing/pull/87 with more changes to readme.

**Pull request closed without merging**
