### PR TITLE
Remove the jarsigner for now and do some pom cleanup.

### PR DESCRIPTION
**Pull request by pilhuhn**
Signed-off-by: Heiko W. Rupp <hrupp@redhat.com>

@pavolloffay @Steve-Fontes

### CODE REVIEW

**Comment by pavolloffay** [comment]
What is the status of travis integration? Is it enabled? Can I create a PR? Also other question can we use maven wrapper here?

**Comment by pilhuhn** [comment]
@pavolloffay I don't have the powers to do so. Perhaps @kwsutter can do. Otherwise we need to open a ticket with the EclipseFdn to clarify this.

**Comment by johnament** [comment]
We can use maven wrapper, as far as I know.  I don't believe travis is supported, we can ask webmaster.  However, we can also setup jenkins jobs to do PR builds.

**Comment by johnament** [comment]
Travis is in fact supported.  So if we want to enable travis we can, probably best to confirm on the google group.

**Comment by pilhuhn** [comment]
@johnament I was not able to enable builds for this in the travis console as I am lacking the rights. Same for Kevin. So I guess we need to go through webmaster(?)

**Comment by johnament** [comment]
Yes, you'd have to go through webmaster to get it enabled I suspect.  At least based on the bugzillas I found in their DB.

**Comment by Steve-Fontes** [comment]
Included these changes in PR 38. Closing this PR.

**Pull request closed without merging**
