### PR TITLE
Method @Traced annotation takes precedence

### LINKED ISSUE #20: @Traced on method should override class level traced
If the `@Traced` annotation is declared on class and there is also `@Traced` defined on a method of the given class then annotation on method should take precedence.

### PR DESCRIPTION
**Pull request by pavolloffay**
Fixes #20

### CODE REVIEW

**Comment by pavolloffay** [comment]
@Steve-Fontes could you please review?

cc @pilhuhn @objectiser

**Comment by pavolloffay** [comment]
> nit: Should method have a capital letter, as with Class? Same should apply to the sentence above.

I have aligned it with the sentence above. Shouldn't it be all small letters?

**Comment by objectiser** [comment]
Yeah that would work aswell - just needs to be consistent 😄

**Comment by pilhuhn** [comment]
@pavolloffay can you please rebase?

**Comment by pavolloffay** [comment]
PR rebased

**Pull request merged**
