### PR TITLE
Add changelog for 2.0

### PR DESCRIPTION
**Pull request by pavolloffay**
Related to #191 

Signed-off-by: Pavol Loffay <ploffay@redhat.com>

@fmhwong could you please review?

### CODE REVIEW

**Comment by pavolloffay** [comment]
@radcortez could you please review?

**Comment by fmhwong** [comment]
Probably should include #190 and #193

**Comment by pavolloffay** [comment]
Correct I will update the PR

**Comment by pavolloffay** [comment]
@fmhwong I will skip #190 because we will update the rest client to 2.0.

PR updated

**Comment by fmhwong** [comment]
@pavolloffay You meant skipping #193, right?

**Comment by pavolloffay** [comment]
Yes I will skip #193. The update of MP-Config and Rest Client will be done once we  update them to final versions.

**Pull request merged**
